

import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "./_components/Footer";
import Navbar from "./_components/Navbar";
import MobileNavbar from "./_components/MobileNavbar";
import Head from 'next/head';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function classNames(...classes) {
  return classes.filter(Boolean).join(' ')
}

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <Head>
  <meta name="csrf-token" content="{{ csrf_token() }}" />

</Head>
      <body className={inter.className}>
        <div className="bg-white"> 
        <MobileNavbar></MobileNavbar>
        <Navbar></Navbar>
        {children}
        <Footer></Footer>
        </div>
        
      </body>
    </html>
  );
}
